- become: yes
  hosts: all
  name: html-deploy
  tasks:
    - name: Wait for apt to unlock
      become: yes
      shell:  while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;
      
    - name: Update apt cache and install Nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Creates directory
      file: 
        path : /var/www/ejemplo.com 
        state : directory

    - name: delete default nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: restart nginx

    - name: copy nginx site.conf
      template:
        src: site.conf.j2
        dest: /etc/nginx/sites-enabled/ejemplo.com
        owner: root
        group: root
        mode: '0644'
      notify: restart nginx

    - name: "sync website"
      synchronize:
        src: sites/
        dest: /var/www/ejemplo.com
        archive: no
        checksum: yes
        recursive: yes
        delete: yes
      become: no

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted