// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.time.Duration;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CompraTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.gecko.driver","C:/Users/Israel/Desktop/Codigos/Mingeso/PEP2/P8-selenium/geckodriver.exe");
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void compra() throws InterruptedException {
    driver.get("http://automationpractice.com/index.php");
    driver.manage().window().setSize(new Dimension(948, 858));
    driver.findElement(By.linkText("Sign in")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("iariaspanez@gmail.com");
    driver.findElement(By.id("passwd")).click();
    driver.findElement(By.id("passwd")).sendKeys("qwerty");
    driver.findElement(By.cssSelector(".columns-container")).click();
    driver.findElement(By.cssSelector("#SubmitLogin > span")).click();
    driver.findElement(By.xpath("//a[contains(text(),\'Women\')]")).click();
    driver.findElement(By.cssSelector("li:nth-child(1) > .subcategory-image .replace-2x")).click();
    driver.findElement(By.cssSelector(".ajax_block_product:nth-child(1) .replace-2x")).click();
    new WebDriverWait(driver, 30).until(ExpectedConditions.elementToBeClickable(By.cssSelector(".exclusive > span"))).click();
    new WebDriverWait(driver, 30).until(ExpectedConditions.elementToBeClickable(By.cssSelector(".continue > span"))).click();
    //driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
    //driver.findElement(By.cssSelector(".exclusive > span")).click();
   //driver.findElement(By.cssSelector(".continue > span")).click();
    driver.findElement(By.linkText("Tops")).click();
    driver.findElement(By.cssSelector(".last-item-of-tablet-line .replace-2x")).click();
    driver.findElement(By.cssSelector(".exclusive > span")).click();
    new WebDriverWait(driver, 30).until(ExpectedConditions.elementToBeClickable(By.cssSelector(".button-medium > span"))).click();
    //driver.findElement(By.cssSelector(".button-medium > span")).click();
    driver.findElement(By.cssSelector(".standard-checkout > span")).click();
    driver.findElement(By.cssSelector(".button:nth-child(4) > span")).click();
    driver.findElement(By.id("cgv")).click();
    driver.findElement(By.cssSelector(".standard-checkout > span")).click();
    driver.findElement(By.linkText("Pay by bank wire (order processing will be longer)")).click();
    driver.findElement(By.cssSelector("#cart_navigation span")).click();
    assertThat(driver.findElement(By.cssSelector(".cheque-indent > .dark")).getText(), is("Your order on My Store is complete."));
  }
}
